export const ALL_USERS_DATA_REQUEST = 'ALL_USERS_DATA_REQUEST'
export const ALL_USERS_DATA_SUCCESS = 'ALL_USERS_DATA_SUCCESS'
export const ALL_USERS_DATA_FAIL = 'ALL_USERS_DATA_FAIL'

export const SINGLE_USER_DETAIL_REQUEST = 'SINGLE_USER_DETAIL_REQUEST'
export const SINGLE_USER_DETAIL_SUCCESS = 'SINGLE_USER_DETAIL_SUCCESS'
export const SINGLE_USER_DETAIL_FAIL = 'SINGLE_USER_DETAIL_FAIL'

export const SINGLE_USER_DETAILS_UPDATE_REQUEST = 'SINGLE_USER_DETAILS_UPDATE_REQUEST'
export const SINGLE_USER_DETAILS_UPDATE_SUCCESS = 'SINGLE_USER_DETAILS_UPDATE_SUCCESS'
export const SINGLE_USER_DETAILS_UPDATE_FAIL = 'SINGLE_USER_DETAILS_UPDATE_FAIL'

export const DELETE_SINGLE_USER_REQUEST = 'DELETE_SINGLE_USER_REQUEST'
export const DELETE_SINGLE_USER_SUCCESS = 'DELETE_SINGLE_USER_SUCCESS'
export const DELETE_SINGLE_USER_FAIL = 'DELETE_SINGLE_USER_FAIL'
export const RESET_SINGLE_USER = 'RESET_SINGLE_USER'

export const SINGLE_PRODUCT_DETAIL_REQUEST = 'SINGLE_PRODUCT_DETAIL_REQUEST'
export const SINGLE_PRODUCT_DETAIL_SUCCESS = 'SINGLE_PRODUCT_DETAIL_SUCCESS'
export const SINGLE_PRODUCT_DETAIL_FAIL = 'SINGLE_PRODUCT_DETAIL_FAIL'

export const SINGLE_PRODUCT_UPDATE_REQUEST = 'SINGLE_PRODUCT_UPDATE_REQUEST'
export const SINGLE_PRODUCT_UPDATE_SUCCESS = 'SINGLE_PRODUCT_UPDATE_SUCCESS'
export const SINGLE_PRODUCT_UPDATE_FAIL = 'SINGLE_PRODUCT_UPDATE_FAIL'
export const RESET_PRODUCT_UPDATE = "RESET_PRODUCT_UPDATE"

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'
export const RESET_DELETED_PRODUCT = 'RESET_DELETED_PRODUCT'

export const NEW_PRODUCT_REQUEST = 'NEW_PRODUCT_REQUEST'
export const NEW_PRODUCT_SUCCESS = 'NEW_PRODUCT_SUCCESS'
export const NEW_PRODUCT_FAIL = 'NEW_PRODUCT_FAIL'
export const RESET_NEW_PRODUCT = 'RESET_NEW_PRODUCT'

export const ADMIN_PRODUCT_REQUEST = 'ADMIN_PRODUCT_REQUEST'
export const ADMIN_PRODUCT_SUCCESS = 'ADMIN_PRODUCT_SUCCESS'
export const ADMIN_PRODUCT_FAIL = 'ADMIN_PRODUCT_FAIL'


export const ADMIN_CLEAR_ERROR = 'ADMIN_CLEAR_ERROR'
