export const ADD_TO_CART = 'ADD_TO_CART'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const SAVE_SHIPPING_INFORMATION = 'SAVE_SHIPPING_INFORMATION'

export const REMOVE_ALL_ITEM_FROM_CART = 'REMOVE_ALL_ITEM_FROM_CART'