export const GET_USER_ORDER_DETAIL_REQUEST = "GET_USER_ORDER_DETAIL_REQUEST";
export const GET_USER_ORDER_DETAIL_SUCCESS = "GET_USER_ORDER_DETAIL_SUCCESS";
export const GET_USER_ORDER_DETAIL_FAIL = "GET_USER_ORDER_DETAIL_FAIL";

export const GET_SINGLE_ORDER_DETAIL_REQUEST =
  "GET_SINGLE_ORDER_DETAIL_REQUEST";
export const GET_SINGLE_ORDER_DETAIL_SUCCESS =
  "GET_SINGLE_ORDER_DETAIL_SUCCESS";
export const GET_SINGLE_ORDER_DETAIL_FAIL = "GET_SINGLE_ORDER_DETAIL_FAIL";

export const DELETE_SINGLE_ORDER_REQUEST = "DELETE_SINGLE_ORDER_REQUEST";
export const DELETE_SINGLE_ORDER_SUCCESS = "DELETE_SINGLE_ORDER_SUCCESS";
export const DELETE_SINGLE_ORDER_FAIL = "DELETE_SINGLE_ORDER_FAIL";
export const RESET_SINGLE_ORDER = "RESET_DELETE_SINGLE_ORDER";

export const USER_ORDER_CREATE_REQUEST = "USER_ORDER_CREATE_REQUEST";
export const USER_ORDER_CREATE_SUCCESS = "USER_ORDER_CREATE_SUCCESS";
export const USER_ORDER_CREATE_FAIL = "USER_ORDER_CREATE_FAIL";
export const RESET_USER_PRODUCT_ORDER = "RESET_USER_PRODUCT_ORDER";

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";
export const RESET_DELETE_ORDER = "RESET_DELETE_ORDER";

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const RESET_ORDER_UPDATE = "RESET_ORDER_UPDATE";

export const ORDER_CLEAR_ERROR = "ORDER_CLEAR_ERROR";
