export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_SECCESS = 'SEARCH_PRODUCT_SECCESS'
export const SEARCH_PRODUCT_FAIL =  'SEARCH_PRODUCT_FAIL'
export const RESET_SEARCH_PRODUCT = 'RESET_SEARCH_PRODUCT'

export const CLEAR_SEARCH_ERROR = 'CLEAR_SEARCH_ERROR'