export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const RESET_UPDATE_PROFILE = 'RESET_UPDATE_PROFILE'
export const UPDATE_PROFILE_FAIL = 'UPDATE_PROFILE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'